# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: golang:1.20
    steps:
    
    - name: Build
      run: CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o anime main.go

    - name: Github Release
      uses: elgohr/Github-Release-Action@v5
      with:
        # The name of the release to publish
        title: anime
        # Directory of the repository that the should create the release
        workdir: ./anime

                

